name: Update RST
'on':
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
    run-all:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update RST
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD
          python ./scripts/rst.py

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet && echo 'No changes to commit' || echo '::set-output name=changed::true'

      - name: Save changes
        run:  |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions [bot]"
          git add .
          git commit -m "Update RST timeline"
        if: steps.changes.outputs.changed == 'true'

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changes.outputs.changed == 'true'
          
